version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynet

  app2:
    build: ./app
    links:
      - db
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - mynet

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
    networks:
      - mynet

  nginx:
    image: nginx
    ports:
      - "8080:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx configuration
    depends_on:
      - app
    networks:
      - mynet

networks:
  mynet: